apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
    #targetPort: 80
    nodePort: 30000 
  selector:
    app: primeiro-pod

    /*Com o nodePort você mostra a aponta diretamente a porta utilizada*/